In [ ]:
import pandas as pd
import numpy as np
from numpy import mean
from numpy import std
from numpy import ravel
from sklearn.metrics import accuracy_score


Mound GG drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#from sklearn.model_selection import train_test_split
#data = pd.read_csv("/content/drive/MyDrive/Full_data/kronodroid_emu_dynamic.csv")
#label = data.filter(items=['label'], axis=1)
#data = data.drop(columns=['label'])
#data_train, data_test, label_train, label_test = train_test_split(data, label, test_size=0.20, random_state=50)

from sklearn.model_selection import train_test_split
data = pd.read_csv("/content/drive/MyDrive/Malware/Data/custom/DATA_ML.csv")
data = data.drop(columns=["apk_name"])
label = pd.read_csv("/content/drive/MyDrive/Malware/Data/custom/LABEL_ML.csv")
data_train, data_test, label_train, label_test = train_test_split(data, label, test_size=0.20, random_state=50)
print(data_train.shape)
print(data_test.shape)

(13794, 3998)
(3449, 3998)


In [ ]:
def convertTo1D(x : pd.DataFrame):
  retu = []
  for i in x.values:
    if all(i == [0, 0, 0, 0]):
      retu.append(0)
    else:
      retu.append(1)
  return retu

In [ ]:
#def df_label():
 # df_label_1d=[]
  #for index, row in label.iterrows():
  #  if row['Adware'] == 1:
  #    df_label_1d.append(1)
  #  elif row['Banking'] == 1:
  #    df_label_1d.append(1)
  #  elif row['Riskware'] == 1:
  #    df_label_1d.append(1)
  #  elif row['SMS'] == 1:
  #    df_label_1d.append(1)
 #   else:
 #     df_label_1d.append(0)
 # return df_label_1d

#df_label_1d()

In [ ]:
label_train=convertTo1D(label_train)
label_test=convertTo1D(label_test)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
def DT():
  model = DecisionTreeClassifier(criterion="entropy")
  model.fit(data_train, label_train)
  yhat = model.predict(data_test)
  yhat = yhat.round()
  acc = accuracy_score(label_test, yhat, sample_weight=None)
  print("Accuracy Score: %.3f (%.3f)" % (mean(acc), std(acc)))

  from sklearn.metrics import confusion_matrix
  print('Confusion matrix:')
  print(confusion_matrix(label_test, yhat))

  tn, fp, fn, tp = confusion_matrix(label_test, yhat).ravel()
  fpr = fp /(fp+tn)
  print("False positive rate: %.3f (%.3f)" % (mean(fpr),std(fpr)))

  from sklearn.metrics import f1_score
  f1 = f1_score(label_test, yhat)
  print("F1 Score: %.3f (%.3f)" % (mean(f1),std(f1)))

  from sklearn.metrics import precision_score
  preci = precision_score(label_test, yhat)
  print("Precision Score: %.3f (%.3f)" % (mean(preci),std(preci)))

  from sklearn.metrics import recall_score
  recall = recall_score(label_test, yhat)
  print("Recall Score: %.3f (%.3f)" % (mean(recall),std(recall)))

  from sklearn.metrics import roc_auc_score
  auc = roc_auc_score(label_test, yhat)
  print("AUC Score: %.3f (%.3f)" % (mean(recall),std(recall)))







In [ ]:
DT()

Accuracy Score: 0.966 (0.000)
Confusion matrix:
[[ 723   58]
 [  58 2610]]
False positive rate: 0.074 (0.000)
F1 Score: 0.978 (0.000)
Precision Score: 0.978 (0.000)
Recall Score: 0.978 (0.000)
AUC Score: 0.978 (0.000)


In [ ]:
from sklearn.linear_model import LogisticRegression
def LR():
  model = LogisticRegression(random_state=0,solver="newton-cg")
  model.fit(data_train, label_train)
  yhat = model.predict(data_test)
  yhat = yhat.round()
  acc = accuracy_score(label_test, yhat, sample_weight=None)
  print("Accuracy Score: %.3f (%.3f)" % (mean(acc), std(acc)))

  from sklearn.metrics import confusion_matrix
  print('Confusion matrix:')
  print(confusion_matrix(label_test, yhat))

  tn, fp, fn, tp = confusion_matrix(label_test, yhat).ravel()
  fpr = fp /(fp+tn)
  print("False positive rate: %.3f (%.3f)" % (mean(fpr),std(fpr)))

  from sklearn.metrics import f1_score
  f1 = f1_score(label_test, yhat)
  print("F1 Score: %.3f (%.3f)" % (mean(f1),std(f1)))

  from sklearn.metrics import precision_score
  preci = precision_score(label_test, yhat)
  print("Precision Score: %.3f (%.3f)" % (mean(preci),std(preci)))

  from sklearn.metrics import recall_score
  recall = recall_score(label_test, yhat)
  print("Recall Score: %.3f (%.3f)" % (mean(recall),std(recall)))

  from sklearn.metrics import roc_auc_score
  auc = roc_auc_score(label_test, yhat)
  print("AUC Score: %.3f (%.3f)" % (mean(recall),std(recall)))

In [ ]:
LR()

Accuracy Score: 0.974 (0.000)
Confusion matrix:
[[ 729   52]
 [  38 2630]]
False positive rate: 0.067 (0.000)
F1 Score: 0.983 (0.000)
Precision Score: 0.981 (0.000)
Recall Score: 0.986 (0.000)
AUC Score: 0.986 (0.000)


In [ ]:
from sklearn.svm import LinearSVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
def SVM():
  # model = make_pipeline(StandardScaler(), LinearSVC(random_state=0))
  model = LinearSVC(random_state=0, verbose=1)
  model.fit(data_train, label_train)

  yhat = model.predict(data_test)

  yhat = yhat.round()
  acc = accuracy_score(label_test, yhat,sample_weight=None)
  print("Accuracy Score: %.3f (%.3f)" % (mean(acc), std(acc)))

  from sklearn.metrics import confusion_matrix
  print('Confusion matrix:')
  print(confusion_matrix(label_test, yhat))

  tn, fp, fn, tp = confusion_matrix(label_test, yhat).ravel()
  fpr = fp /(fp+tn)
  print("False positive rate: %.3f (%.3f)" % (mean(fpr),std(fpr)))

  from sklearn.metrics import f1_score
  f1 = f1_score(label_test, yhat)
  print("F1 Score: %.3f (%.3f)" % (mean(f1),std(f1)))

  from sklearn.metrics import precision_score
  preci = precision_score(label_test, yhat)
  print("Precision Score: %.3f (%.3f)" % (mean(preci),std(preci)))

  from sklearn.metrics import recall_score
  recall = recall_score(label_test, yhat)
  print("Recall Score: %.3f (%.3f)" % (mean(recall),std(recall)))

  from sklearn.metrics import roc_auc_score
  auc = roc_auc_score(label_test, yhat)
  print("AUC Score: %.3f (%.3f)" % (mean(recall),std(recall)))

In [ ]:
SVM()

[LibLinear]

/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Accuracy Score: 0.972 (0.000)
Confusion matrix:
[[ 730   51]
 [  45 2623]]
False positive rate: 0.065 (0.000)
F1 Score: 0.982 (0.000)
Precision Score: 0.981 (0.000)
Recall Score: 0.983 (0.000)
AUC Score: 0.983 (0.000)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
def KNN():
  model = KNeighborsClassifier(n_neighbors=5)
  model.fit(data_train, label_train)
  yhat = model.predict(data_test)
  yhat = yhat.round()
  acc = accuracy_score(label_test, yhat, sample_weight=None)
  print("Accuracy Score: %.3f (%.3f)" % (mean(acc), std(acc)))

  from sklearn.metrics import confusion_matrix
  print('Confusion matrix:')
  print(confusion_matrix(label_test, yhat))

  tn, fp, fn, tp = confusion_matrix(label_test, yhat).ravel()
  fpr = fp /(fp+tn)
  print("False positive rate: %.3f (%.3f)" % (mean(fpr),std(fpr)))

  from sklearn.metrics import f1_score
  f1 = f1_score(label_test, yhat)
  print("F1 Score: %.3f (%.3f)" % (mean(f1),std(f1)))

  from sklearn.metrics import precision_score
  preci = precision_score(label_test, yhat)
  print("Precision Score: %.3f (%.3f)" % (mean(preci),std(preci)))

  from sklearn.metrics import recall_score
  recall = recall_score(label_test, yhat)
  print("Recall Score: %.3f (%.3f)" % (mean(recall),std(recall)))

  from sklearn.metrics import roc_auc_score
  auc = roc_auc_score(label_test, yhat)
  print("AUC Score: %.3f (%.3f)" % (mean(recall),std(recall)))

In [ ]:
KNN()

Accuracy Score: 0.971 (0.000)
Confusion matrix:
[[ 732   49]
 [  52 2616]]
False positive rate: 0.063 (0.000)
F1 Score: 0.981 (0.000)
Precision Score: 0.982 (0.000)
Recall Score: 0.981 (0.000)
AUC Score: 0.981 (0.000)


In [ ]:
import xgboost as xgb

def XGB():
  model = xgb.XGBClassifier(objective="binary:logistic", verbosity=1) # binary
  model.fit(data_train, label_train)
  yhat = model.predict(data_test)
  yhat = yhat.round()
  acc = accuracy_score(label_test, yhat, sample_weight=None)
  print("Accuracy Score: %.3f (%.3f)" % (mean(acc), std(acc)))

  from sklearn.metrics import confusion_matrix
  print('Confusion matrix:')
  print(confusion_matrix(label_test, yhat))

  tn, fp, fn, tp = confusion_matrix(label_test, yhat).ravel()
  fpr = fp /(fp+tn)
  print("False positive rate: %.3f (%.3f)" % (mean(fpr),std(fpr)))

  from sklearn.metrics import f1_score
  f1 = f1_score(label_test, yhat)
  print("F1 Score: %.3f (%.3f)" % (mean(f1),std(f1)))

  from sklearn.metrics import precision_score
  preci = precision_score(label_test, yhat)
  print("Precision Score: %.3f (%.3f)" % (mean(preci),std(preci)))

  from sklearn.metrics import recall_score
  recall = recall_score(label_test, yhat)
  print("Recall Score: %.3f (%.3f)" % (mean(recall),std(recall)))

  from sklearn.metrics import roc_auc_score
  auc = roc_auc_score(label_test, yhat)
  print("AUC Score: %.3f (%.3f)" % (mean(recall),std(recall)))

In [ ]:
XGB()

Accuracy Score: 0.967 (0.000)
Confusion matrix:
[[ 704   77]
 [  37 2631]]
False positive rate: 0.099 (0.000)
F1 Score: 0.979 (0.000)
Precision Score: 0.972 (0.000)
Recall Score: 0.986 (0.000)
AUC Score: 0.986 (0.000)


In [ ]:
from sklearn.neural_network import MLPClassifier

def MLP():
  model = MLPClassifier(verbose=True)
  model.fit(data_train, label_train)
  yhat = model.predict(data_test)
  yhat = yhat.round()
  acc = accuracy_score(label_test, yhat, sample_weight=None)
  print("Accuracy Score: %.3f (%.3f)" % (mean(acc), std(acc)))

  from sklearn.metrics import confusion_matrix
  print('Confusion matrix:')
  print(confusion_matrix(label_test, yhat))

  tn, fp, fn, tp = confusion_matrix(label_test, yhat).ravel()
  fpr = fp /(fp+tn)
  print("False positive rate: %.3f (%.3f)" % (mean(fpr),std(fpr)))

  from sklearn.metrics import f1_score
  f1 = f1_score(label_test, yhat)
  print("F1 Score: %.3f (%.3f)" % (mean(f1),std(f1)))

  from sklearn.metrics import precision_score
  preci = precision_score(label_test, yhat)
  print("Precision Score: %.3f (%.3f)" % (mean(preci),std(preci)))

  from sklearn.metrics import recall_score
  recall = recall_score(label_test, yhat)
  print("Recall Score: %.3f (%.3f)" % (mean(recall),std(recall)))

  from sklearn.metrics import roc_auc_score
  auc = roc_auc_score(label_test, yhat)
  print("AUC Score: %.3f (%.3f)" % (mean(recall),std(recall)))

In [ ]:
MLP()

Iteration 1, loss = 0.32198234
Iteration 2, loss = 0.13875563
Iteration 3, loss = 0.10534536
Iteration 4, loss = 0.09038905
Iteration 5, loss = 0.08155267
Iteration 6, loss = 0.07631804
Iteration 7, loss = 0.07215619
Iteration 8, loss = 0.06998941
Iteration 9, loss = 0.06725189
Iteration 10, loss = 0.06508581
Iteration 11, loss = 0.06333949
Iteration 12, loss = 0.06169963
Iteration 13, loss = 0.06034806
Iteration 14, loss = 0.05880385
Iteration 15, loss = 0.05783847
Iteration 16, loss = 0.05634537
Iteration 17, loss = 0.05523277
Iteration 18, loss = 0.05459132
Iteration 19, loss = 0.05340409
Iteration 20, loss = 0.05219040
Iteration 21, loss = 0.05096522
Iteration 22, loss = 0.05010669
Iteration 23, loss = 0.04918839
Iteration 24, loss = 0.04843754
Iteration 25, loss = 0.04798825
Iteration 26, loss = 0.04742994
Iteration 27, loss = 0.04604799
Iteration 28, loss = 0.04554330
Iteration 29, loss = 0.04500284
Iteration 30, loss = 0.04413877
Iteration 31, loss = 0.04420879
Iteration 32, los

In [ ]:
def MLPOptimized():
  model = MLPClassifier(solver='adam', activation='relu', hidden_layer_sizes=(150, 200), batch_size=200, verbose=True)
  model.fit(data_train, label_train)
  yhat = model.predict(data_test)
  yhat = yhat.round()
  acc = accuracy_score(label_test, yhat, sample_weight=None)
  print("Accuracy Score: %.3f (%.3f)" % (mean(acc), std(acc)))

  from sklearn.metrics import confusion_matrix
  print('Confusion matrix:')
  print(confusion_matrix(label_test, yhat))

  tn, fp, fn, tp = confusion_matrix(label_test, yhat).ravel()
  fpr = fp /(fp+tn)
  print("False positive rate: %.3f (%.3f)" % (mean(fpr),std(fpr)))

  from sklearn.metrics import f1_score
  f1 = f1_score(label_test, yhat)
  print("F1 Score: %.3f (%.3f)" % (mean(f1),std(f1)))

  from sklearn.metrics import precision_score
  preci = precision_score(label_test, yhat)
  print("Precision Score: %.3f (%.3f)" % (mean(preci),std(preci)))

  from sklearn.metrics import recall_score
  recall = recall_score(label_test, yhat)
  print("Recall Score: %.3f (%.3f)" % (mean(recall),std(recall)))

  from sklearn.metrics import roc_auc_score
  auc = roc_auc_score(label_test, yhat)
  print("AUC Score: %.3f (%.3f)" % (mean(recall),std(recall)))

In [ ]:
MLPOptimized()

Iteration 1, loss = 0.22751033
Iteration 2, loss = 0.08456843
Iteration 3, loss = 0.07122572
Iteration 4, loss = 0.05912782
Iteration 5, loss = 0.05333379
Iteration 6, loss = 0.04627686
Iteration 7, loss = 0.04241553
Iteration 8, loss = 0.04081947
Iteration 9, loss = 0.03717956
Iteration 10, loss = 0.03525257
Iteration 11, loss = 0.03445271
Iteration 12, loss = 0.03381061
Iteration 13, loss = 0.03079040
Iteration 14, loss = 0.03206704
Iteration 15, loss = 0.03074092
Iteration 16, loss = 0.02881061
Iteration 17, loss = 0.02904927
Iteration 18, loss = 0.02806423
Iteration 19, loss = 0.02692170
Iteration 20, loss = 0.02709143
Iteration 21, loss = 0.02637685
Iteration 22, loss = 0.02574259
Iteration 23, loss = 0.02572801
Iteration 24, loss = 0.02527227
Iteration 25, loss = 0.02565548
Iteration 26, loss = 0.02394278
Iteration 27, loss = 0.02464007
Iteration 28, loss = 0.02527257
Iteration 29, loss = 0.02462500


In [ ]:
import pandas as pd
import numpy
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, Conv1D, Flatten, MaxPooling1D
from numpy import unique
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
import warnings
import sys

X_ = data_train.values.reshape(data_train.shape[0], data_train.shape[1], 1)

modelCnn = Sequential()
modelCnn.add(Conv1D(64, 2, activation="relu", input_shape=(data_train.shape[1],1)))
modelCnn.add(Dense(16, activation="relu"))
modelCnn.add(MaxPooling1D())
modelCnn.add(Flatten())
modelCnn.add(Dense(2, activation = 'softmax'))
modelCnn.compile(loss = 'sparse_categorical_crossentropy', optimizer = "adam", metrics = ['accuracy'])
X_ = np.array(X_)
#print(X_)

label_train = np.array(label_train)

print(label_train)
#data_test = np.array(data_test)
Y_ = data_test.values.reshape(data_test.shape[0], data_test.shape[1], 1)
Y_ = np.array(Y_)
#print(Y_)

label_test = np.array(label_test)
#print(label_test)

yhat = modelCnn.predict(data_test)
yhat = yhat.round()

yhat = np.array(yhat)
modelCnn.summary()
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt
from keras.models import Sequential

from keras.layers import Embedding, LSTM, GlobalAveragePooling2D
from keras.layers import Dense, Dropout, Conv1D, MaxPool1D, BatchNormalization
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

predict_x=modelCnn.predict(data_test)
classes_x=np.argmax(predict_x,axis=1)

#optimizer = adam(lr=.0001)
#modelCnn.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
modelCnn.compile(optimizer='adam',loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
#history = modelCnn.fit(data_train, label_train, validation_split=0.2, epochs=150, batch_size=100) #original batch_size = 512
history = modelCnn.fit(data_train, label_train, validation_split=0.1, epochs=10, batch_size=512) #original batch_size = 512

#y_pred = modelCnn.predict_classes(data_test)
#acc = accuracy_score(label_test, yhat, sample_weight=None)
#print("Accuracy Score: %.3f (%.3f)" % (mean(acc), std(acc)))
#modelCnn.fit(X_, label_train, batch_size=64, epochs=150, verbose=0)




[1 1 1 ... 1 0 1]
108/108 [==============================] - 3s 30ms/step
Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_5 (Conv1D)           (None, 3997, 64)          192       
                                                                 
 dense_10 (Dense)            (None, 3997, 16)          1040      
                                                                 
 max_pooling1d_5 (MaxPooling  (None, 1998, 16)         0         
 1D)                                                             
                                                                 
 flatten_5 (Flatten)         (None, 31968)             0         
                                                                 
 dense_11 (Dense)            (None, 2)                 63938     
                                                                 
Total params: 65,170
Trainable params: 65,170


/usr/local/lib/python3.9/dist-packages/keras/backend.py:5612: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


25/25 [==============================] - ETA: 0s - loss: 0.5426 - accuracy: 0.7419

/usr/local/lib/python3.9/dist-packages/keras/backend.py:5612: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


25/25 [==============================] - 47s 2s/step - loss: 0.5426 - accuracy: 0.7419 - val_loss: 0.4607 - val_accuracy: 0.7572
Epoch 2/10
25/25 [==============================] - 33s 1s/step - loss: 0.3712 - accuracy: 0.8287 - val_loss: 0.2769 - val_accuracy: 0.8891
Epoch 3/10
25/25 [==============================] - 35s 1s/step - loss: 0.2242 - accuracy: 0.9111 - val_loss: 0.1842 - val_accuracy: 0.9304
Epoch 4/10
25/25 [==============================] - 33s 1s/step - loss: 0.1651 - accuracy: 0.9289 - val_loss: 0.1538 - val_accuracy: 0.9384
Epoch 5/10
25/25 [==============================] - 34s 1s/step - loss: 0.1365 - accuracy: 0.9434 - val_loss: 0.1372 - val_accuracy: 0.9457
Epoch 6/10
25/25 [==============================] - 34s 1s/step - loss: 0.1180 - accuracy: 0.9526 - val_loss: 0.1307 - val_accuracy: 0.9449
Epoch 7/10
25/25 [==============================] - 33s 1s/step - loss: 0.1060 - accuracy: 0.9586 - val_loss: 0.1191 - val_accuracy: 0.9609
Epoch 8/10
25/25 [=============